### ISSUE TITLE
Unknown Relocation Type

### ISSUE THREAD

**Issue by IanBriggs** [PRUNERS/FLiT#263]
When using FLiT bisect I have run into an error stemming from pyelftools.
A relocation type used in a compiled file is not known.
I have used an older version of FLiT when we used objdump and the bisection went through.

I suggest that we use pyelftools, but catch the exception thrown by it and fall back to using objdump.

Later I will upload an object file to demonstrate the issue.

**Comment by IanBriggs** [comment]
(file is attached)
[flit_test_mesh_3_issue_1554_bisect_c6257f8636.o.zip](https://github.com/PRUNERS/FLiT/files/3065847/flit_test_mesh_3_issue_1554_bisect_c6257f8636.o.zip)


The error trace is:

Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ibriggs/FLIT/FLIT_DEVEL/scripts/flitcli/flit_bisect.py", line 1782, in auto_bisect_worker
    num, libs, srcs, syms, ret = run_bisect(row_args)
  File "/home/ibriggs/FLIT/FLIT_DEVEL/scripts/flitcli/flit_bisect.py", line 1659, in run_bisect
    args, bisect_path, replacements, sources, differing_source)
  File "/home/ibriggs/FLIT/FLIT_DEVEL/scripts/flitcli/flit_bisect.py", line 1297, in search_for_symbol_problems
    extract_symbols(differing_source, os.path.join(args.directory, 'obj'))
  File "/home/ibriggs/FLIT/FLIT_DEVEL/scripts/flitcli/flit_bisect.py", line 542, in extract_symbols
    _extract_symbols_memos[fobj] = elf.extract_symbols(fobj, fname)
  File "/home/ibriggs/FLIT/FLIT_DEVEL/scripts/flitcli/flitelf.py", line 144, in extract_symbols
    locs = _locate_symbols(elffile, fsyms)
  File "/home/ibriggs/FLIT/FLIT_DEVEL/scripts/flitcli/flitelf.py", line 218, in _locate_symbols
    dwarfinfo = elffile.get_dwarf_info()
  File "/usr/lib/python3/dist-packages/elftools/elf/elffile.py", line 174, in get_dwarf_info
    relocate_dwarf_sections)
  File "/usr/lib/python3/dist-packages/elftools/elf/elffile.py", line 402, in _read_dwarf_section
    section_stream, reloc_section)
  File "/usr/lib/python3/dist-packages/elftools/elf/relocation.py", line 124, in apply_section_relocations
    self._do_apply_relocation(stream, reloc, symtab)
  File "/usr/lib/python3/dist-packages/elftools/elf/relocation.py", line 158, in _do_apply_relocation
    'Unsupported relocation type: %s' % reloc_type)
elftools.common.exceptions.ELFRelocationError: Unsupported relocation type: 21
